// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version 2.5.1 DO NOT EDIT.
package openapi

import (
	"context"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Список архивных дел
	// (GET /api/archive)
	ListArchive(w http.ResponseWriter, r *http.Request, params ListArchiveParams)
	// Получить запись архива
	// (GET /api/archive/{id})
	GetArchiveByID(w http.ResponseWriter, r *http.Request, id UUID)
	// Обновить запись архива (judge)
	// (PATCH /api/archive/{id})
	PatchArchive(w http.ResponseWriter, r *http.Request, id UUID)
	// Login и выдача JWT
	// (POST /api/auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Завершение сессии (no-op для stateless JWT)
	// (POST /api/auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Текущий аутентифицированный пользователь
	// (GET /api/auth/me)
	GetCurrentUser(w http.ResponseWriter, r *http.Request)
	// Список активных дел (пагинация)
	// (GET /api/cases)
	ListCases(w http.ResponseWriter, r *http.Request, params ListCasesParams)
	// Создать новое дело (citizen)
	// (POST /api/cases)
	CreateCase(w http.ResponseWriter, r *http.Request)
	// Поиск дел с сортировкой
	// (POST /api/cases/search)
	SearchCases(w http.ResponseWriter, r *http.Request)
	// Получить дело по ID
	// (GET /api/cases/{id})
	GetCaseByID(w http.ResponseWriter, r *http.Request, id UUID)
	// Принять дело в производство и назначить прокурора (registrar)
	// (POST /api/cases/{id}/accept)
	AcceptCase(w http.ResponseWriter, r *http.Request, id UUID)
	// Бюрократически отклонить дело без суда (registrar)
	// (POST /api/cases/{id}/dismiss)
	DismissCase(w http.ResponseWriter, r *http.Request, id UUID)
	// Список документов по делу (judge)
	// (GET /api/cases/{id}/documents)
	ListCaseDocuments(w http.ResponseWriter, r *http.Request, id UUID)
	// Получить заключение прокурора по делу (judge/prosecutor)
	// (GET /api/cases/{id}/opinion)
	GetCaseOpinion(w http.ResponseWriter, r *http.Request, id UUID)
	// Подать предварительное заключение прокурора (prosecutor)
	// (POST /api/cases/{id}/opinion)
	FileOpinion(w http.ResponseWriter, r *http.Request, id UUID)
	// Вынести финальный приговор (только judge)
	// (POST /api/cases/{id}/verdict)
	SetCaseVerdict(w http.ResponseWriter, r *http.Request, id UUID)
	// Подать донос (citizen)
	// (POST /api/complaints)
	CreateComplaint(w http.ResponseWriter, r *http.Request)
	// Все доносы по делу (judge/prosecutor)
	// (GET /api/complaints/{case_id})
	ListComplaintsByCase(w http.ResponseWriter, r *http.Request, caseId UUID)
	// Прикрепить улику по URL (prosecutor)
	// (POST /api/complaints/{id}/evidence)
	AttachEvidence(w http.ResponseWriter, r *http.Request, id UUID)
	// Сгенерировать документ по шаблону (prosecutor)
	// (POST /api/documents/generate)
	GenerateDocument(w http.ResponseWriter, r *http.Request)
	// Получить документ
	// (GET /api/documents/{id})
	GetDocumentByID(w http.ResponseWriter, r *http.Request, id UUID)
	// Health check (для compose healthcheck и SLA check_1)
	// (GET /api/health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Дела, ожидающие приговора судьи
	// (GET /api/hearings)
	ListHearings(w http.ResponseWriter, r *http.Request)
	// Список пользователей по роли
	// (GET /api/users)
	ListUsersByRole(w http.ResponseWriter, r *http.Request, params ListUsersByRoleParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Список архивных дел
// (GET /api/archive)
func (_ Unimplemented) ListArchive(w http.ResponseWriter, r *http.Request, params ListArchiveParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить запись архива
// (GET /api/archive/{id})
func (_ Unimplemented) GetArchiveByID(w http.ResponseWriter, r *http.Request, id UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Обновить запись архива (judge)
// (PATCH /api/archive/{id})
func (_ Unimplemented) PatchArchive(w http.ResponseWriter, r *http.Request, id UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Login и выдача JWT
// (POST /api/auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Завершение сессии (no-op для stateless JWT)
// (POST /api/auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Текущий аутентифицированный пользователь
// (GET /api/auth/me)
func (_ Unimplemented) GetCurrentUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Список активных дел (пагинация)
// (GET /api/cases)
func (_ Unimplemented) ListCases(w http.ResponseWriter, r *http.Request, params ListCasesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Создать новое дело (citizen)
// (POST /api/cases)
func (_ Unimplemented) CreateCase(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Поиск дел с сортировкой
// (POST /api/cases/search)
func (_ Unimplemented) SearchCases(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить дело по ID
// (GET /api/cases/{id})
func (_ Unimplemented) GetCaseByID(w http.ResponseWriter, r *http.Request, id UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Принять дело в производство и назначить прокурора (registrar)
// (POST /api/cases/{id}/accept)
func (_ Unimplemented) AcceptCase(w http.ResponseWriter, r *http.Request, id UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Бюрократически отклонить дело без суда (registrar)
// (POST /api/cases/{id}/dismiss)
func (_ Unimplemented) DismissCase(w http.ResponseWriter, r *http.Request, id UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Список документов по делу (judge)
// (GET /api/cases/{id}/documents)
func (_ Unimplemented) ListCaseDocuments(w http.ResponseWriter, r *http.Request, id UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить заключение прокурора по делу (judge/prosecutor)
// (GET /api/cases/{id}/opinion)
func (_ Unimplemented) GetCaseOpinion(w http.ResponseWriter, r *http.Request, id UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Подать предварительное заключение прокурора (prosecutor)
// (POST /api/cases/{id}/opinion)
func (_ Unimplemented) FileOpinion(w http.ResponseWriter, r *http.Request, id UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Вынести финальный приговор (только judge)
// (POST /api/cases/{id}/verdict)
func (_ Unimplemented) SetCaseVerdict(w http.ResponseWriter, r *http.Request, id UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Подать донос (citizen)
// (POST /api/complaints)
func (_ Unimplemented) CreateComplaint(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Все доносы по делу (judge/prosecutor)
// (GET /api/complaints/{case_id})
func (_ Unimplemented) ListComplaintsByCase(w http.ResponseWriter, r *http.Request, caseId UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Прикрепить улику по URL (prosecutor)
// (POST /api/complaints/{id}/evidence)
func (_ Unimplemented) AttachEvidence(w http.ResponseWriter, r *http.Request, id UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Сгенерировать документ по шаблону (prosecutor)
// (POST /api/documents/generate)
func (_ Unimplemented) GenerateDocument(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить документ
// (GET /api/documents/{id})
func (_ Unimplemented) GetDocumentByID(w http.ResponseWriter, r *http.Request, id UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check (для compose healthcheck и SLA check_1)
// (GET /api/health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Дела, ожидающие приговора судьи
// (GET /api/hearings)
func (_ Unimplemented) ListHearings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Список пользователей по роли
// (GET /api/users)
func (_ Unimplemented) ListUsersByRole(w http.ResponseWriter, r *http.Request, params ListUsersByRoleParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListArchive operation middleware
func (siw *ServerInterfaceWrapper) ListArchive(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListArchiveParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListArchive(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetArchiveByID operation middleware
func (siw *ServerInterfaceWrapper) GetArchiveByID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArchiveByID(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchArchive operation middleware
func (siw *ServerInterfaceWrapper) PatchArchive(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchArchive(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCases operation middleware
func (siw *ServerInterfaceWrapper) ListCases(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCasesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "assigned_to" -------------

	err = runtime.BindQueryParameter("form", true, false, "assigned_to", r.URL.Query(), &params.AssignedTo)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "assigned_to", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCases(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCase operation middleware
func (siw *ServerInterfaceWrapper) CreateCase(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCase(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchCases operation middleware
func (siw *ServerInterfaceWrapper) SearchCases(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchCases(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCaseByID operation middleware
func (siw *ServerInterfaceWrapper) GetCaseByID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCaseByID(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AcceptCase operation middleware
func (siw *ServerInterfaceWrapper) AcceptCase(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AcceptCase(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DismissCase operation middleware
func (siw *ServerInterfaceWrapper) DismissCase(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DismissCase(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCaseDocuments operation middleware
func (siw *ServerInterfaceWrapper) ListCaseDocuments(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCaseDocuments(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCaseOpinion operation middleware
func (siw *ServerInterfaceWrapper) GetCaseOpinion(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCaseOpinion(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// FileOpinion operation middleware
func (siw *ServerInterfaceWrapper) FileOpinion(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FileOpinion(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetCaseVerdict operation middleware
func (siw *ServerInterfaceWrapper) SetCaseVerdict(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetCaseVerdict(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateComplaint operation middleware
func (siw *ServerInterfaceWrapper) CreateComplaint(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateComplaint(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListComplaintsByCase operation middleware
func (siw *ServerInterfaceWrapper) ListComplaintsByCase(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "case_id" -------------
	var caseId UUID

	err = runtime.BindStyledParameterWithOptions("simple", "case_id", chi.URLParam(r, "case_id"), &caseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "case_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListComplaintsByCase(w, r, caseId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AttachEvidence operation middleware
func (siw *ServerInterfaceWrapper) AttachEvidence(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AttachEvidence(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GenerateDocument operation middleware
func (siw *ServerInterfaceWrapper) GenerateDocument(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GenerateDocument(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDocumentByID operation middleware
func (siw *ServerInterfaceWrapper) GetDocumentByID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDocumentByID(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListHearings operation middleware
func (siw *ServerInterfaceWrapper) ListHearings(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListHearings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUsersByRole operation middleware
func (siw *ServerInterfaceWrapper) ListUsersByRole(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUsersByRoleParams

	// ------------- Required query parameter "role" -------------

	if paramValue := r.URL.Query().Get("role"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "role"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "role", r.URL.Query(), &params.Role)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "role", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsersByRole(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/archive", wrapper.ListArchive)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/archive/{id}", wrapper.GetArchiveByID)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/archive/{id}", wrapper.PatchArchive)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/auth/me", wrapper.GetCurrentUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/cases", wrapper.ListCases)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/cases", wrapper.CreateCase)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/cases/search", wrapper.SearchCases)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/cases/{id}", wrapper.GetCaseByID)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/cases/{id}/accept", wrapper.AcceptCase)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/cases/{id}/dismiss", wrapper.DismissCase)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/cases/{id}/documents", wrapper.ListCaseDocuments)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/cases/{id}/opinion", wrapper.GetCaseOpinion)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/cases/{id}/opinion", wrapper.FileOpinion)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/cases/{id}/verdict", wrapper.SetCaseVerdict)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/complaints", wrapper.CreateComplaint)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/complaints/{case_id}", wrapper.ListComplaintsByCase)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/complaints/{id}/evidence", wrapper.AttachEvidence)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/documents/generate", wrapper.GenerateDocument)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/documents/{id}", wrapper.GetDocumentByID)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/hearings", wrapper.ListHearings)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/users", wrapper.ListUsersByRole)
	})

	return r
}
