// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version 2.5.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xd63IbR3Z+la5JqkhWxgQoyV6ZW/xBido1XYytEkk7WZHFHWGa5NjADDQzUEyrWMWL",
	"Hdslr7VyNnEl2V3tevMvfyCKsCDSgF7h9CvkSVJ9untu6MEAFC+QLf+QBWC65/S5fP2d0xfdNypere65",
	"1A0DY/q+EVQ2ac3Cv876lU3nHr3hhv4W/1z3vTr1Q4fir5b41V6zQv5x3fNr/G+GbYX0jdCpUcM0wq06",
	"NaaNIPQdd8PYNo2KFdA1x041aDQc2zANt1GtWneq1JgO/QbVta1aQeCsO9Rec72Q8j4K29h0nbq25aKI",
	"9BOrVucPG4teI2h8TMms8yl1TQL/xfbhBXThmPzfZ/8xpRN83XGt6to96ttOBTv7e5+uG9PG35Vi9ZWk",
	"7kofyMe2TUOMtd/Dy8vzc/zJgLohdSs0LSn8N7TZl9CCDrShRdguHEAXnkAXDtkDk1wqk3K5TOAYWmyv",
	"WInbpuHTuw3Hp7YxfdtAvccqyo7STNl4NerNu/MRFaOTHnLTCiubt+jdBg1QN5ZtO6HjuVb1ZsJlhERp",
	"J9LY9NRUn1Rorx56xnLdCqjGy4PA2XCpvVb3vYBWGqHnS/+1qtX3143p24NYdzVrmW3TsBrh5ql1dpLY",
	"qPjUCoeNX5//oLNSTqS9621aLllw6B3qh9lIe1v3imEi5u6a26ilXjgV9ei4Id2gPj4YWmEjKOqWO8Ci",
	"eHLbNBL+RvElt42NhlMNt3hYVO42nDCkGD5OUHOCgNrG6onCTw0iHYhCz5HkKWOt5jjvbKVC62EiDNOe",
	"3OPAxSrOyJvuIU+M6yhprhiRB9WsTxaouxFuGtOXyleumkbNcdUXU0VQnmj85tSlwrYh/STb7OrU20Xt",
	"MsPX2Qc7ztPEnHCNXFX41Ao8d3hdZOSS3eRJ8X7dcR3xmowl4rl4kGhbd6pDgsXgfdd9WnVqjmv5W4MC",
	"/c24SQLzT+DkplQgF1o7U/SErFJc9nX6cST7T2gxz1yLEVYp2LF9a51349Wpy8FHzkiGaWxSyxfdVqqe",
	"hKAeK1z3avWq5bgaB0xNQYNoakiXOckMQ+85Np+112wrtAaax6IWDb+aJpa+MwivHHw8CkaG8pFYybKD",
	"YjBXFiuC0uGscSogGI8rF/rmvEqjRi/E3zzO+EItPzmJLw6jW26ykL6UdyjxE90V+opS9q+pS/1TdZZ4",
	"QAmHmXrr8tUrJ/cY2aduIDd83/OvezZNQt8dy17z5YhMo+EKbTmfIvqte/4dx7YRFF0vXFv3Gq5U43pV",
	"IC/ngD7PHijvXQuP+N5bNKh7ro7/i4a92pSC9lNlPKJt06jRILA2Msmd496zqo5NKj61qRs6VjUwCtXJ",
	"O4z706lSakxaO36dT++ulafe+c0Hk5OT//TPvyl8VVZpCWNJyM31Nj0U938db6N72TvUqoab8byYflPM",
	"7eOB8t8tkYDqwvoe9QPJiOI2lyenJsuFMkZ8XPWRIzBvPB/Smj4OB8lEeEdeTN2KHlcsTxd9RtyTTtwF",
	"b8Nx89MGKwj+xfPtLBBcKmbsjYAHXw/bf2tIAIm6MWNh+owjL5JtLydz9b1qoUVu8Wc4LHofU7SHTYOK",
	"79RDNI/x7odLxKpUaBAQfMIkS0sLZIZMbRo5ejlpDiYEiPuQ4ptieDq1SM8o4BKnxsBTZPqlqEYRmdYN",
	"ViPTUAl8j61uSedQXVSc0PkULRBzf8M0PmrYGxSl23CC0Lf0c80itfxUoSzjoY5PK6EMeJuuW40qx865",
	"G4vXDTOSYBY/4Ze6d/Dhh6kO3iyb3BBOjbe/VC6jFcQnbbXEW18PaLqLZJuyto1vU3/tzlZa8gR30Uh6",
	"N5v5vvlWkUvc1RodAyUF5pUp8d8b+McV/sdV9VH9JxhEqgTdI+JyQHWT/wmopEKfRGU3VQr7xcvxz2Ew",
	"LAnLsTjowWuXjYGKVglITsJPIVvl+lxwglA/NeYi9Nnr4eRj1g3zdKBH9lJQPjoR0qaL4z3VJx1jGqr4",
	"ntHfoOgdjThA/MhZcVqjakGqnyypxSuZSg7Ku+xEBtvv+SjTzWFdUT9mRvbewaNJKg3fCbcWee9ixNeo",
	"5VN/tsFNc9+4g59+pfDm3Q+XsGrcj4iQdd+rkZvvLy6RklV3SjyBKlU5UTIJdwFiBeS3szKrQso8TcRL",
	"yUqjXL5cwV7wr/S3k4Yplge54EKYGC42w7BubPNxOO66J3IkN7SE04gwM+CP0IIf4EgBH/saOtCFFoHv",
	"ocU+xw/H0IWn0GZfQIvtwpH4+RH7hu1A1yTwZ7YHh9CCY/ILURROjh7+yvbx1yfQgSZ7SOAFHEOT7bHP",
	"oMt24EdokvTb2QP2OYGn0GW72LTJdtgu24MDAn8UH6A5ucKn+6pToZJXytH84/wSUkInRACdX15cml+a",
	"n00kByqr2BbFO6vu4FflycvIZcNNNLIwjPAP/nlDTL5REjNvG9MGR03p0tjWt2o0pH6Aa0YOf9XdBvU5",
	"wEjpBA+QBrNeghBsm/oXSJqgfUMBX9he5eEiiDqq4FK5rDxGhp1Vr1edCo6/9JGskscvckJaC4ZFACmF",
	"5fvWlvDUrPfAC2izXejCEX/+SnlqKKEKawFRbqJ7+Z+gBU04YHvoqW14Bl04gCZ0BDY0ajWLg15KSoIu",
	"+jm04UC5MsYGj0prg/uGwh1jlfeS9LTSfcfeznW3X1Plbde25ueMlzTX4FbSKOY7aIoRs6+T422OlIm4",
	"KFfOVxTCMQ6eo8U70M26yWOEuH32BbTZHlfdszw96pxFDzEcsmIAENlnNOuJ6vpgA5Sp7SqiYGWz1/9w",
	"R0GMd7Kidc2zt07b8VJ7F7bTE7lcXB8R3+/itMZd7hhNLiOgfM4RwD3+GNpwyCEHnhM4wC0ph0Kay+cc",
	"BCLxHsH4+3NkrYL4I+M4hon+oB3xNqTFXqCjCPjz2QRLqkZ4zlGSruvprPE3tgsvOIMcxYiYOndpWmwH",
	"JWkRjv/sEduTHznBhY74kEo5jOnbq0nvRZUTaBM4YA+QFn8BTSISjshJeVbS66FeI+zrovz3Hme50ltS",
	"zRp1JLkYx2fUd3qLXovtsl1oQ5uMu94bXp0r/pg9JEFohbTKk7N3P1yaKNBljfZjZ9cbvk/dEAtUZxh7",
	"2L9ORY95PsY+gzbPo0bYQt9Di2d87Cto88hssn22x03F9qDNxWf/Cm0+FNFaBbDKD2W32ISPM9diPOEP",
	"+iZv1/GJVz91y+kyWhgbzMLJvXa8y4x5/0f4FdtjO2gMot+GScY5kZzAhd5ekaI2oWcMT0zPPj9V1aZX",
	"Ni+9AL7H9gi8YDtcIjIOHUUAS7FbTPTPl+GIR34mXybj8AKa8BTaWDfikPAwCc8iujErktNaRrLvUaQO",
	"crwj3h66HEygS/DFz3AKfcT2CO+JjItgmcGNXSaJtoDMVKqWUwsm5drexIrLZ+DH8O/wF/gW/hf+k1TU",
	"zqBJsij2jcYz9CO2x3bZQ6KsBT8icMWVtLYoZKWhSSwLXhf1yrNgjr1bQgeij1OnKkBOWEnLCPr+mjmO",
	"TpgTtczaE8sqmDClEvlVVzDbFhxDl4zLlrrwTU3WpQAXY/O5qlisVdP2WYRGejn4DLKq052G/gIteMb2",
	"xcSMJngwIlGDqTUS0t0RpqKPoYsT0ZGaddguTg9sB2FakNAj6MLzQt8tqt1ym5514TYXV/8gQvFnjWHf",
	"SY9ssa9UeegVKBErEEXKjd6jYUDnURfu9faShadbknCdGe+3ESpIBjeNbGtSkq2ZMaRbYybh9Go8lUdM",
	"TPpelc7MjMXfjk2uuPAYSyktMSdzJSVUdEBkxyrNMInCII6OcMAzfiSs+txFR8bECR5Jxs6pAH9WnC99",
	"GumcS4ZF2CRM1YYOe8jRYjSmMeE4bI/ts13CE2DO/tGlsILBXWvnYthYvKvt3FEsMlinGM5ik6bA7EBp",
	"kc8IGMpiiZ//1hZ9PsO8L8LBjNKhScYjFUwMNDmX5Nael8erSaKBIUwjYwgSp3/MFVdutJmJNhb9kueH",
	"WUBKL0UcELncwPmI2hY0897ywoIOouSZtp8GRmUO6J0zSKV3O/V1/i7bgyPcGtMRvo+ey80YLyQly5gj",
	"iGivkSsfueT2JjjiWJOu2aRtn+VpT3hKRtTepROglNygVly6nouePMeoP+vUN96/N1wVllsA5wf4Ua4l",
	"dOHgdb6Tznf6VGE12hM5h/Bstq9ZE49dVevJiaMy/ZJidUzmjLlnfBpHr6ojOGbf8CAXa4Y/y/xUo4eB",
	"WJ5uX1NPP70MTudfqWWDC0t2zRMzRJVZjpHZ9+bEb/pkcyaztMCT2541C97//HuLN24tYVdrMqQCkyzf",
	"nJtduoHfBmTxxpLinWPyAPqYjin+yqmmwu30KZz2ZNMFrC4MGe1ieVmuO5ipqgvyfPalylvYLrr6l/ho",
	"mz0crUUKlaNePMuLfZ2UEhiisroWdPALwn7HJ5tI4yPGCbkwb18wALN9+CHjoToAjlZgcA6BQ9wkscMR",
	"WWyUUNv6B8Tm8f44rJnuEwdShl2SnSbjUxMEnqJALSE1UUyQIPPeQVpte5UN6oqJA2PwiWDhbJ/I1/9y",
	"xR2/NBEFblGCTv4BV2t78vFEb5cnhkjYJwmOsgVP2D4+l54dFDgTaK+46GzHmFlwI+A1JEQivA69FwVf",
	"+iA6ufMKp/qZg1Qjl+aLwtVTsZjJdsSSfgczwBZ0kjOEcOYd9kDg2KtQA5D7EQ+hDUfclUdlzhjZjcPf",
	"KuOzPa6oz8SmFHVcCXenZfxlHFMo/sARdElP5tQDo2oTSZC/+C23hURXB51RDU5/0c15U7holK93ifwk",
	"domkGMohzvtdtqvfGhLHgi5ASvfl7TXb/QtkUYNrWwNXxuN7cUa/UJYIkZNUylD/r2tkRTWyb/mEn9AY",
	"ezBU1aLIlTlvVnel5SP/bBhalU11wU+vJ6cHFfVP0JNfJVaYvcPovJeo+846f0PAP8K6FfrtERL9F6N1",
	"9Gv51sJFJ/wXkcOrCaUni9evSCvTiXol2xemZfsiuJdvLeTmv7qIjurgpQ155Vt+LKtL4ebiewjOIpLy",
	"7qA754hK3Magt1piySGxL1tNBRe+WJooMVx8VGVXb5Llkh11Kkbxq6RideWSHP/WLenE7l20x1GZW+5z",
	"fBUWJU/Le18ffR92X2Naff1dcBPvG+zneuJGwrNcREzdeajn2DwWDzjPJljpfIIbBZr47wD0O9opeiaV",
	"TVr5mIzLg4koQUCJGLr4DdpkcWFWPLg2lYzbYCsIaS2tMd9xN5K7CHqWsjjaHuD+hq+ElBwpmmyHPSCY",
	"ZJmqGrmtTkvCAR6ljA7pxOVU+T5cxUpUPmQ7xKdjaItKiK64yXO2d5TM55E/JW+EHDaDSi8CwfOffdYv",
	"K3fpmBcrK02TQBd+kGum3+Cpz1ZPwQyacssM+xrafQpljQBnkzyf/pNYLIFOvMtojE92WL59gpW5xMKU",
	"EEL+jz3iWKQKu80Jorx1jO2vuON4CqCDiylHbFdNqioNnJgk2nhKVQEdW2x05nOfSXyvSk1iezVK3lhx",
	"5bYhEX8YKy14nhcny1wJ17ZuiSvPBji9Ki9HO9lEK+5mO5+iRuoyuqHrGtojwlyRr2scyRpHpjgdRUpJ",
	"lqn7bRPKVbEkmRLndRGcngDTF6ndXuX+FVD/nr6mseBVrCqx6T0injFMcZ0xXnE2XSpV+e+bXhBOXy1f",
	"LeO/xyLf3wMRv88eN+cpvdhrQXAVJL4qIHFumUupORT9++TZ1QR6pEuKga7pH5IlpafIF36QuU/cOM42",
	"NT38W8T/m8LP9Hvgot5iYqXp7Lt4GStnJOoGFE3jv3IMROB9om65+B104BDdpc0lYQ8S59IFV9le3f7/",
	"AAAA//8CmdZw6WoAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
