// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version 2.5.1 DO NOT EDIT.
package openapi

import (
	"encoding/json"
	"fmt"
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for CaseVerdict.
const (
	CaseVerdictAcquitted CaseVerdict = "acquitted"
	CaseVerdictDismissed CaseVerdict = "dismissed"
	CaseVerdictGuilty    CaseVerdict = "guilty"
)

// Defines values for CaseStatus.
const (
	Assigned CaseStatus = "assigned"
	Closed   CaseStatus = "closed"
	Draft    CaseStatus = "draft"
	Hearing  CaseStatus = "hearing"
	Open     CaseStatus = "open"
)

// Defines values for ErrorCode.
const (
	BadRequest    ErrorCode = "bad_request"
	Conflict      ErrorCode = "conflict"
	Forbidden     ErrorCode = "forbidden"
	InternalError ErrorCode = "internal_error"
	NotFound      ErrorCode = "not_found"
	Unauthorized  ErrorCode = "unauthorized"
)

// Defines values for PreliminaryVerdict.
const (
	PreliminaryVerdictAcquitted PreliminaryVerdict = "acquitted"
	PreliminaryVerdictDismissed PreliminaryVerdict = "dismissed"
	PreliminaryVerdictGuilty    PreliminaryVerdict = "guilty"
)

// Defines values for Role.
const (
	Citizen    Role = "citizen"
	Judge      Role = "judge"
	Prosecutor Role = "prosecutor"
	Registrar  Role = "registrar"
)

// Defines values for SearchRequestDirection.
const (
	ASC  SearchRequestDirection = "ASC"
	DESC SearchRequestDirection = "DESC"
)

// Defines values for Verdict.
const (
	Acquitted Verdict = "acquitted"
	Dismissed Verdict = "dismissed"
	Guilty    Verdict = "guilty"
)

// ArchiveEntry defines model for ArchiveEntry.
type ArchiveEntry struct {
	ArchivedAt     time.Time           `json:"archived_at"`
	CaseID         *openapi_types.UUID `json:"case_id"`
	ClassifiedNote *string             `json:"classified_note"`
	Defendant      string              `json:"defendant"`
	FinalVerdict   Verdict             `json:"final_verdict"`
	ID             UUID                `json:"id"`
	Sentence       *string             `json:"sentence"`
}

// ArchivePatchRequest defines model for ArchivePatchRequest.
type ArchivePatchRequest struct {
	ClassifiedNote       *string                `json:"classified_note,omitempty"`
	FinalVerdict         *Verdict               `json:"final_verdict,omitempty"`
	Sentence             *string                `json:"sentence,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Case defines model for Case.
type Case struct {
	AssignedProsecutorID *UUID        `json:"assigned_prosecutor_id"`
	AuthorID             *UUID        `json:"author_id"`
	ClassifiedNote       *string      `json:"classified_note"`
	CreatedAt            time.Time    `json:"created_at"`
	Crime                string       `json:"crime"`
	Defendant            string       `json:"defendant"`
	ID                   UUID         `json:"id"`
	SeqNum               int          `json:"seq_num"`
	Status               CaseStatus   `json:"status"`
	Verdict              *CaseVerdict `json:"verdict"`
}

// CaseVerdict defines model for Case.Verdict.
type CaseVerdict string

// CaseAcceptRequest defines model for CaseAcceptRequest.
type CaseAcceptRequest struct {
	ProsecutorID UUID `json:"prosecutor_id"`
}

// CaseCreateRequest defines model for CaseCreateRequest.
type CaseCreateRequest struct {
	Crime     string `json:"crime"`
	Defendant string `json:"defendant"`
	Text      string `json:"text"`
}

// CaseDismissRequest defines model for CaseDismissRequest.
type CaseDismissRequest struct {
	Reason string `json:"reason"`
}

// CaseOpinion defines model for CaseOpinion.
type CaseOpinion struct {
	CaseID             UUID               `json:"case_id"`
	FiledAt            time.Time          `json:"filed_at"`
	ID                 UUID               `json:"id"`
	PreliminaryVerdict PreliminaryVerdict `json:"preliminary_verdict"`
	ProsecutorID       UUID               `json:"prosecutor_id"`
	Reasoning          string             `json:"reasoning"`
}

// CaseStatus defines model for CaseStatus.
type CaseStatus string

// Complaint defines model for Complaint.
type Complaint struct {
	AuthorID     UUID      `json:"author_id"`
	CaseID       UUID      `json:"case_id"`
	CreatedAt    time.Time `json:"created_at"`
	EvidenceData *string   `json:"evidence_data"`
	EvidenceURL  *string   `json:"evidence_url"`
	ID           UUID      `json:"id"`
	Text         string    `json:"text"`
}

// ComplaintCreateRequest defines model for ComplaintCreateRequest.
type ComplaintCreateRequest struct {
	CaseID UUID   `json:"case_id"`
	Text   string `json:"text"`
}

// Document defines model for Document.
type Document struct {
	AuthorID  UUID      `json:"author_id"`
	CaseID    UUID      `json:"case_id"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
	ID        UUID      `json:"id"`
	Template  string    `json:"template"`
}

// DocumentGenerateRequest defines model for DocumentGenerateRequest.
type DocumentGenerateRequest struct {
	CaseID   UUID   `json:"case_id"`
	Template string `json:"template"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code    ErrorCode `json:"code"`
		Message string    `json:"message"`
	} `json:"error"`
	RequestID *string `json:"request_id,omitempty"`
}

// EvidenceRequest defines model for EvidenceRequest.
type EvidenceRequest struct {
	URL string `json:"url"`
}

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	Status  string `json:"status"`
	Version string `json:"version"`
}

// HearingItem defines model for HearingItem.
type HearingItem struct {
	Case    Case        `json:"case"`
	Opinion CaseOpinion `json:"opinion"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	Dome string `json:"dome"`
	Role Role   `json:"role"`

	// Token JWT access token, TTL = 1h
	Token  string `json:"token"`
	UserID UUID   `json:"user_id"`
}

// OpinionCreateRequest defines model for OpinionCreateRequest.
type OpinionCreateRequest struct {
	PreliminaryVerdict PreliminaryVerdict `json:"preliminary_verdict"`
	Reasoning          string             `json:"reasoning"`
}

// PreliminaryVerdict defines model for PreliminaryVerdict.
type PreliminaryVerdict string

// Role defines model for Role.
type Role string

// SearchRequest defines model for SearchRequest.
type SearchRequest struct {
	Direction *SearchRequestDirection `json:"direction,omitempty"`
	Limit     *int                    `json:"limit,omitempty"`
	Offset    *int                    `json:"offset,omitempty"`
	OrderBy   *string                 `json:"order_by,omitempty"`
	Q         string                  `json:"q"`
}

// SearchRequestDirection defines model for SearchRequest.Direction.
type SearchRequestDirection string

// UUID defines model for UUID.
type UUID = openapi_types.UUID

// User defines model for User.
type User struct {
	CreatedAt time.Time `json:"created_at"`
	Dome      string    `json:"dome"`
	ID        UUID      `json:"id"`
	Role      Role      `json:"role"`
	Username  string    `json:"username"`
}

// UserListItem defines model for UserListItem.
type UserListItem struct {
	Dome     string `json:"dome"`
	ID       UUID   `json:"id"`
	Role     Role   `json:"role"`
	Username string `json:"username"`
}

// Verdict defines model for Verdict.
type Verdict string

// VerdictRequest defines model for VerdictRequest.
type VerdictRequest struct {
	Reasoning string  `json:"reasoning"`
	Sentence  *string `json:"sentence,omitempty"`
	Verdict   Verdict `json:"verdict"`
}

// VerdictResult defines model for VerdictResult.
type VerdictResult struct {
	ArchiveEntry ArchiveEntry `json:"archive_entry"`
	Case         Case         `json:"case"`
	Document     Document     `json:"document"`
}

// ListArchiveParams defines parameters for ListArchive.
type ListArchiveParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListCasesParams defines parameters for ListCases.
type ListCasesParams struct {
	Limit  *int        `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int        `form:"offset,omitempty" json:"offset,omitempty"`
	Status *CaseStatus `form:"status,omitempty" json:"status,omitempty"`

	// AssignedTo Фильтр по assigned_prosecutor_id (UUID)
	AssignedTo *UUID `form:"assigned_to,omitempty" json:"assigned_to,omitempty"`
}

// ListUsersByRoleParams defines parameters for ListUsersByRole.
type ListUsersByRoleParams struct {
	Role Role `form:"role" json:"role"`
}

// PatchArchiveJSONRequestBody defines body for PatchArchive for application/json ContentType.
type PatchArchiveJSONRequestBody = ArchivePatchRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// CreateCaseJSONRequestBody defines body for CreateCase for application/json ContentType.
type CreateCaseJSONRequestBody = CaseCreateRequest

// SearchCasesJSONRequestBody defines body for SearchCases for application/json ContentType.
type SearchCasesJSONRequestBody = SearchRequest

// AcceptCaseJSONRequestBody defines body for AcceptCase for application/json ContentType.
type AcceptCaseJSONRequestBody = CaseAcceptRequest

// DismissCaseJSONRequestBody defines body for DismissCase for application/json ContentType.
type DismissCaseJSONRequestBody = CaseDismissRequest

// FileOpinionJSONRequestBody defines body for FileOpinion for application/json ContentType.
type FileOpinionJSONRequestBody = OpinionCreateRequest

// SetCaseVerdictJSONRequestBody defines body for SetCaseVerdict for application/json ContentType.
type SetCaseVerdictJSONRequestBody = VerdictRequest

// CreateComplaintJSONRequestBody defines body for CreateComplaint for application/json ContentType.
type CreateComplaintJSONRequestBody = ComplaintCreateRequest

// AttachEvidenceJSONRequestBody defines body for AttachEvidence for application/json ContentType.
type AttachEvidenceJSONRequestBody = EvidenceRequest

// GenerateDocumentJSONRequestBody defines body for GenerateDocument for application/json ContentType.
type GenerateDocumentJSONRequestBody = DocumentGenerateRequest

// Getter for additional properties for ArchivePatchRequest. Returns the specified
// element and whether it was found
func (a ArchivePatchRequest) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ArchivePatchRequest
func (a *ArchivePatchRequest) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ArchivePatchRequest to handle AdditionalProperties
func (a *ArchivePatchRequest) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["classified_note"]; found {
		err = json.Unmarshal(raw, &a.ClassifiedNote)
		if err != nil {
			return fmt.Errorf("error reading 'classified_note': %w", err)
		}
		delete(object, "classified_note")
	}

	if raw, found := object["final_verdict"]; found {
		err = json.Unmarshal(raw, &a.FinalVerdict)
		if err != nil {
			return fmt.Errorf("error reading 'final_verdict': %w", err)
		}
		delete(object, "final_verdict")
	}

	if raw, found := object["sentence"]; found {
		err = json.Unmarshal(raw, &a.Sentence)
		if err != nil {
			return fmt.Errorf("error reading 'sentence': %w", err)
		}
		delete(object, "sentence")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ArchivePatchRequest to handle AdditionalProperties
func (a ArchivePatchRequest) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.ClassifiedNote != nil {
		object["classified_note"], err = json.Marshal(a.ClassifiedNote)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'classified_note': %w", err)
		}
	}

	if a.FinalVerdict != nil {
		object["final_verdict"], err = json.Marshal(a.FinalVerdict)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'final_verdict': %w", err)
		}
	}

	if a.Sentence != nil {
		object["sentence"], err = json.Marshal(a.Sentence)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'sentence': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
