// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"database/sql"
	"github.com/TakuyaYagam1/iustitia/config"
	"github.com/wahrwelt-kit/go-logkit"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config, logger logkit.Logger, db *sql.DB) (*App, error) {
	sqlStore := ProvideSQLStore(db)
	user := ProvideUserUseCase(sqlStore, cfg, logger)
	complaint := ProvideComplaintUseCase(sqlStore, logger)
	usecaseCase := ProvideCaseUseCase(sqlStore, logger)
	document := ProvideDocumentUseCase(sqlStore, logger)
	archive := ProvideArchiveUseCase(sqlStore, logger)
	serverDeps := ProvideServerDeps(user, complaint, usecaseCase, document, archive, logger)
	server := ProvideRESTServer(serverDeps)
	router := ProvideRouter(cfg, logger, server)
	httpServer := ProvideHTTPServer(cfg, router)
	app := ProvideApp(httpServer)
	return app, nil
}
