// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cases.sql

package sqlc

import (
	"context"
)

const acceptCase = `-- name: AcceptCase :one
UPDATE cases
SET status                 = 'assigned',
    assigned_prosecutor_id = ?
WHERE id = ? AND status IN ('draft', 'open')
RETURNING id, seq_num, defendant, crime, status, verdict, classified_note, author_id, assigned_prosecutor_id, created_at
`

type AcceptCaseParams struct {
	AssignedProsecutorID *string `json:"assigned_prosecutor_id"`
	ID                   string  `json:"id"`
}

func (q *Queries) AcceptCase(ctx context.Context, arg AcceptCaseParams) (Case, error) {
	row := q.db.QueryRowContext(ctx, acceptCase, arg.AssignedProsecutorID, arg.ID)
	var i Case
	err := row.Scan(
		&i.ID,
		&i.SeqNum,
		&i.Defendant,
		&i.Crime,
		&i.Status,
		&i.Verdict,
		&i.ClassifiedNote,
		&i.AuthorID,
		&i.AssignedProsecutorID,
		&i.CreatedAt,
	)
	return i, err
}

const createCase = `-- name: CreateCase :one
INSERT INTO cases (id, seq_num, defendant, crime, status, author_id)
VALUES (?, (SELECT COALESCE(MAX(seq_num), 0) + 1 FROM cases), ?, ?, 'draft', ?)
RETURNING id, seq_num, defendant, crime, status, verdict, classified_note, author_id, assigned_prosecutor_id, created_at
`

type CreateCaseParams struct {
	ID        string  `json:"id"`
	Defendant string  `json:"defendant"`
	Crime     string  `json:"crime"`
	AuthorID  *string `json:"author_id"`
}

func (q *Queries) CreateCase(ctx context.Context, arg CreateCaseParams) (Case, error) {
	row := q.db.QueryRowContext(ctx, createCase,
		arg.ID,
		arg.Defendant,
		arg.Crime,
		arg.AuthorID,
	)
	var i Case
	err := row.Scan(
		&i.ID,
		&i.SeqNum,
		&i.Defendant,
		&i.Crime,
		&i.Status,
		&i.Verdict,
		&i.ClassifiedNote,
		&i.AuthorID,
		&i.AssignedProsecutorID,
		&i.CreatedAt,
	)
	return i, err
}

const dismissCase = `-- name: DismissCase :execrows
DELETE FROM cases
WHERE id = ? AND status IN ('draft', 'open')
`

func (q *Queries) DismissCase(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, dismissCase, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const finalizeCaseVerdict = `-- name: FinalizeCaseVerdict :one
UPDATE cases
SET status  = 'closed',
    verdict = ?
WHERE id = ? AND status = 'hearing'
RETURNING id, seq_num, defendant, crime, status, verdict, classified_note, author_id, assigned_prosecutor_id, created_at
`

type FinalizeCaseVerdictParams struct {
	Verdict *string `json:"verdict"`
	ID      string  `json:"id"`
}

func (q *Queries) FinalizeCaseVerdict(ctx context.Context, arg FinalizeCaseVerdictParams) (Case, error) {
	row := q.db.QueryRowContext(ctx, finalizeCaseVerdict, arg.Verdict, arg.ID)
	var i Case
	err := row.Scan(
		&i.ID,
		&i.SeqNum,
		&i.Defendant,
		&i.Crime,
		&i.Status,
		&i.Verdict,
		&i.ClassifiedNote,
		&i.AuthorID,
		&i.AssignedProsecutorID,
		&i.CreatedAt,
	)
	return i, err
}

const getCaseByID = `-- name: GetCaseByID :one
SELECT id, seq_num, defendant, crime, status, verdict, classified_note, author_id, assigned_prosecutor_id, created_at
FROM cases
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetCaseByID(ctx context.Context, id string) (Case, error) {
	row := q.db.QueryRowContext(ctx, getCaseByID, id)
	var i Case
	err := row.Scan(
		&i.ID,
		&i.SeqNum,
		&i.Defendant,
		&i.Crime,
		&i.Status,
		&i.Verdict,
		&i.ClassifiedNote,
		&i.AuthorID,
		&i.AssignedProsecutorID,
		&i.CreatedAt,
	)
	return i, err
}

const listCases = `-- name: ListCases :many
SELECT id, seq_num, defendant, crime, status, verdict, classified_note, author_id, assigned_prosecutor_id, created_at
FROM cases
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListCasesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListCases(ctx context.Context, arg ListCasesParams) ([]Case, error) {
	rows, err := q.db.QueryContext(ctx, listCases, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Case{}
	for rows.Next() {
		var i Case
		if err := rows.Scan(
			&i.ID,
			&i.SeqNum,
			&i.Defendant,
			&i.Crime,
			&i.Status,
			&i.Verdict,
			&i.ClassifiedNote,
			&i.AuthorID,
			&i.AssignedProsecutorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCasesByAssignee = `-- name: ListCasesByAssignee :many
SELECT id, seq_num, defendant, crime, status, verdict, classified_note, author_id, assigned_prosecutor_id, created_at
FROM cases
WHERE assigned_prosecutor_id = ?
  AND status IN ('assigned', 'hearing')
ORDER BY created_at DESC
`

func (q *Queries) ListCasesByAssignee(ctx context.Context, assignedProsecutorID *string) ([]Case, error) {
	rows, err := q.db.QueryContext(ctx, listCasesByAssignee, assignedProsecutorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Case{}
	for rows.Next() {
		var i Case
		if err := rows.Scan(
			&i.ID,
			&i.SeqNum,
			&i.Defendant,
			&i.Crime,
			&i.Status,
			&i.Verdict,
			&i.ClassifiedNote,
			&i.AuthorID,
			&i.AssignedProsecutorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCasesByStatus = `-- name: ListCasesByStatus :many
SELECT id, seq_num, defendant, crime, status, verdict, classified_note, author_id, assigned_prosecutor_id, created_at
FROM cases
WHERE status = ?
ORDER BY created_at DESC
`

func (q *Queries) ListCasesByStatus(ctx context.Context, status string) ([]Case, error) {
	rows, err := q.db.QueryContext(ctx, listCasesByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Case{}
	for rows.Next() {
		var i Case
		if err := rows.Scan(
			&i.ID,
			&i.SeqNum,
			&i.Defendant,
			&i.Crime,
			&i.Status,
			&i.Verdict,
			&i.ClassifiedNote,
			&i.AuthorID,
			&i.AssignedProsecutorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCaseHearing = `-- name: MarkCaseHearing :one
UPDATE cases
SET status = 'hearing'
WHERE id = ? AND status = 'assigned' AND assigned_prosecutor_id = ?
RETURNING id, seq_num, defendant, crime, status, verdict, classified_note, author_id, assigned_prosecutor_id, created_at
`

type MarkCaseHearingParams struct {
	ID                   string  `json:"id"`
	AssignedProsecutorID *string `json:"assigned_prosecutor_id"`
}

func (q *Queries) MarkCaseHearing(ctx context.Context, arg MarkCaseHearingParams) (Case, error) {
	row := q.db.QueryRowContext(ctx, markCaseHearing, arg.ID, arg.AssignedProsecutorID)
	var i Case
	err := row.Scan(
		&i.ID,
		&i.SeqNum,
		&i.Defendant,
		&i.Crime,
		&i.Status,
		&i.Verdict,
		&i.ClassifiedNote,
		&i.AuthorID,
		&i.AssignedProsecutorID,
		&i.CreatedAt,
	)
	return i, err
}
