// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: documents.sql

package sqlc

import (
	"context"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (id, case_id, author_id, content, template)
VALUES (?, ?, ?, ?, ?)
RETURNING id, case_id, author_id, content, template, created_at
`

type CreateDocumentParams struct {
	ID       string `json:"id"`
	CaseID   string `json:"case_id"`
	AuthorID string `json:"author_id"`
	Content  string `json:"content"`
	Template string `json:"template"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, createDocument,
		arg.ID,
		arg.CaseID,
		arg.AuthorID,
		arg.Content,
		arg.Template,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.AuthorID,
		&i.Content,
		&i.Template,
		&i.CreatedAt,
	)
	return i, err
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT id, case_id, author_id, content, template, created_at
FROM documents
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetDocumentByID(ctx context.Context, id string) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocumentByID, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.AuthorID,
		&i.Content,
		&i.Template,
		&i.CreatedAt,
	)
	return i, err
}

const listDocumentsByCase = `-- name: ListDocumentsByCase :many
SELECT id, case_id, author_id, content, template, created_at
FROM documents
WHERE case_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListDocumentsByCase(ctx context.Context, caseID string) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentsByCase, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.CaseID,
			&i.AuthorID,
			&i.Content,
			&i.Template,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
