// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type Archive struct {
	ID             string    `json:"id"`
	CaseID         *string   `json:"case_id"`
	Defendant      string    `json:"defendant"`
	FinalVerdict   string    `json:"final_verdict"`
	Sentence       *string   `json:"sentence"`
	ClassifiedNote *string   `json:"classified_note"`
	ArchivedAt     time.Time `json:"archived_at"`
}

type Case struct {
	ID                   string    `json:"id"`
	SeqNum               int64     `json:"seq_num"`
	Defendant            string    `json:"defendant"`
	Crime                string    `json:"crime"`
	Status               string    `json:"status"`
	Verdict              *string   `json:"verdict"`
	ClassifiedNote       *string   `json:"classified_note"`
	AuthorID             *string   `json:"author_id"`
	AssignedProsecutorID *string   `json:"assigned_prosecutor_id"`
	CreatedAt            time.Time `json:"created_at"`
}

type CaseOpinion struct {
	ID                 string    `json:"id"`
	CaseID             string    `json:"case_id"`
	ProsecutorID       string    `json:"prosecutor_id"`
	PreliminaryVerdict string    `json:"preliminary_verdict"`
	Reasoning          string    `json:"reasoning"`
	FiledAt            time.Time `json:"filed_at"`
}

type Complaint struct {
	ID           string    `json:"id"`
	CaseID       string    `json:"case_id"`
	AuthorID     string    `json:"author_id"`
	Text         string    `json:"text"`
	EvidenceUrl  *string   `json:"evidence_url"`
	EvidenceData *string   `json:"evidence_data"`
	CreatedAt    time.Time `json:"created_at"`
}

type Document struct {
	ID        string    `json:"id"`
	CaseID    string    `json:"case_id"`
	AuthorID  string    `json:"author_id"`
	Content   string    `json:"content"`
	Template  string    `json:"template"`
	CreatedAt time.Time `json:"created_at"`
}

type MtbDirective struct {
	ID             int64     `json:"id"`
	DirectiveCode  string    `json:"directive_code"`
	SecretPayload  string    `json:"secret_payload"`
	Classification string    `json:"classification"`
	IssuedAt       time.Time `json:"issued_at"`
}

type User struct {
	ID        string    `json:"id"`
	Username  string    `json:"username"`
	Password  string    `json:"password"`
	Role      string    `json:"role"`
	Dome      string    `json:"dome"`
	CreatedAt time.Time `json:"created_at"`
}
