// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	AcceptCase(ctx context.Context, arg AcceptCaseParams) (Case, error)
	CreateArchiveEntry(ctx context.Context, arg CreateArchiveEntryParams) (Archive, error)
	CreateCase(ctx context.Context, arg CreateCaseParams) (Case, error)
	CreateCaseOpinion(ctx context.Context, arg CreateCaseOpinionParams) (CaseOpinion, error)
	CreateComplaint(ctx context.Context, arg CreateComplaintParams) (Complaint, error)
	CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DismissCase(ctx context.Context, id string) (int64, error)
	FinalizeCaseVerdict(ctx context.Context, arg FinalizeCaseVerdictParams) (Case, error)
	GetArchiveByID(ctx context.Context, id string) (Archive, error)
	GetCaseByID(ctx context.Context, id string) (Case, error)
	GetCaseOpinionByCase(ctx context.Context, caseID string) (CaseOpinion, error)
	GetComplaintByID(ctx context.Context, id string) (Complaint, error)
	GetDirectiveByCode(ctx context.Context, directiveCode string) (MtbDirective, error)
	GetDocumentByID(ctx context.Context, id string) (Document, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListArchive(ctx context.Context, arg ListArchiveParams) ([]Archive, error)
	ListCases(ctx context.Context, arg ListCasesParams) ([]Case, error)
	ListCasesByAssignee(ctx context.Context, assignedProsecutorID *string) ([]Case, error)
	ListCasesByStatus(ctx context.Context, status string) ([]Case, error)
	ListComplaintsByCase(ctx context.Context, caseID string) ([]Complaint, error)
	ListDirectivesPublic(ctx context.Context, arg ListDirectivesPublicParams) ([]MtbDirective, error)
	ListDocumentsByCase(ctx context.Context, caseID string) ([]Document, error)
	ListUsersByRole(ctx context.Context, role string) ([]User, error)
	MarkCaseHearing(ctx context.Context, arg MarkCaseHearingParams) (Case, error)
	UpdateArchiveSafe(ctx context.Context, arg UpdateArchiveSafeParams) (Archive, error)
	UpdateComplaintEvidence(ctx context.Context, arg UpdateComplaintEvidenceParams) (Complaint, error)
}

var _ Querier = (*Queries)(nil)
