// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version 2.5.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xd63IbR3Z+la5JqkhWxgQoyV6ZKf2gRe2aLmatEik7WYnFHc00ybGAGWhmoJhWsYoX",
	"O7ZLXmvlOHEl2V3t2vmXPxAlWBBpQK9w+hXyJFt9untu6MEAFC/QWv4hC8B0z+lz+frcunXPsP16w/eo",
	"F4XG7D0jtDdo3cK/zgX2hnuXXvGiYJN/bgR+gwaRS/FXS/zqrFoR/7jmB3X+N8OxIvpG5NapYRrRZoMa",
	"s0YYBa63bmyZhm2FdNV1MgOaTdcxTMNr1mrWrRo1ZqOgSXVja1YYumsudVY9P6J8jtIxDl2jnmN5SCL9",
	"2Ko3+MPGkt8Mm7cpmXM/oZ5J4L/ZHryAHhyS///0P2d0hK+5nlVbvUsDx7Vxsr8P6Joxa/xdJWFfRfKu",
	"8oF8bMs0xFoHPXz9+sI8fzKkXkQ9m2Yphf+BDvsC2tCFDrQJ24F96MFj6MFTdt8k56qkWq0SOIQ22y1n",
	"4pZpBPRO0w2oY8zeMJDvCYvyqzQzMl6JZ/NvfUTF6qSGXLUie+MavdOkIfLGchw3cn3Pql1NqYygKKtE",
	"GpkeG+vTDO3nQ99aLlsh1Wh5GLrrHnVWG4EfUrsZ+YHUX6tWe3/NmL0xjHRX8pLZMg2rGW0c22RHsQ07",
	"oFY0qv0G/AedlAos7T1/w/LIoktv0SDKW9rbuleMYjF3Vr1mPfPCmXhG14voOg3wwciKmmHZtFwBlsST",
	"W6aR0jeKL7lhrDfdWrTJzcK+03SjiKL5uGHdDUPqGCtHMj+1iKwhCj7HlGeEtVKgvHO2TRtRygyzmtyn",
	"wOUsztGbnaGIjMtIaSEZsQbVrY8XqbcebRiz56oXLppG3fXUFzNlUJ4a/ObMudKxEf04P+zizNtl43LL",
	"18kHJy7ixLxQjUJWBNQKfW90XuToktMUUfF+w/Vc8ZqcJJK9eBhrW3NrI4LF8HM3Alpz665nBZvDAv3V",
	"ZEgK84+g5KZkICdau1P0maxiXP51+nWk509xsUhcSzFWKdhxAmuNT+M3qMfBR+5IhmlsUCsQ09o1X0JQ",
	"nxQu+/VGzXI9jQJmtqBhODWiyhxlh6F3XYfv2quOFVlD7WPxiGZQyzqWgTuMXzn8ehSMjKQjCZPlBOVg",
	"riRWBqWjSeNYQDBZVyH0zft2s07PRN987vFFWv/kKLo4Cm+5yCL6UtqhyE9NV6oritm/oh4NjlVZkgWl",
	"FGbmrfMXLxxdY+ScuoVcCQI/uOw7NA19tyxnNZArMo2mJ7jlfoLot+YHt1zHQVD0/Gh1zW96ko1rNYG8",
	"3AcMePRA+exaeMT3XqNhw/d0/r8Y2M9NSeggViYr2jKNOg1Daz0X3LneXavmOsQOqEO9yLVqoVHKTj5h",
	"Mp+OlZJjUtrJ6wJ6Z7U68+5vPpienv7nf/lN6avyTEsJS0JuobbpoXjw6/gY3cvepVYt2kj2xeybEt8+",
	"WSj/3RIBqM6s79IglB5RMub89Mx0tZTG2B9XcxQQzAcvRLSut8NhIhE+kZ+4bmWPKy9PZ31GMpOO3EV/",
	"3fWKwwYrDP/VD5w8EJwr99ibITe+Pm//rREBJJ7GTIgZsI4iS3b8gsg18GulErnGn+Gw6N+mKA+Hhnbg",
	"NiIUj/Heh8vEsm0ahgSfMMny8iK5RGY2jAK+HDUGEwQkc0jyTbE8HVukZpT4EsfmgWec6ZdyNcqcad1i",
	"NTSNFMD3yeqaVA41he1G7icogcT3N0zjo6azTpG6dTeMAku/1yxRK8gkynIa6gbUjqTBO3TNatY4ds5f",
	"WbpsmDEFc/gJv9S9gy8/ykzwZtXkgnDrfPy5ahWlID5psyX+2lpIs1Okx1S1YwKHBqu3NrOUp3wXDaV3",
	"8pHvm2+VqcQdrdDRUDJgbs+I/97APy7wPy6qj+o/4UFkUtB9JF4PqW7zP4IrqdAnldnNpMJ+8XL+5ygY",
	"loblhBzU4NXzxlBJqxQkp+Gn1Fvl/Fx0w0i/NRYi9Mnz4ehr1i3zeKBHzlKSPjoS0maT433ZJ53HNFLy",
	"Pce/YdE7XnGI+FFQcVqlqiA1iJZM8UqGksP6XU4qgh30fBzpFnhd8Txmjvb+xaNI7GbgRptLfHax4neo",
	"FdBgrslFc8+4hZ9+qfDmvQ+XMWs8yBEha4FfJ1ffX1omFavhVngAValxR8kkXAWIFZLfzsmoCl3mWSJe",
	"Sm42q9XzNs6Cf6W/nTZMUR7khAtiErjYiKKGscXX4XprvoiRvMgSSiPMzIA/QBt+hAMFfOwr6EIP2gS+",
	"hzb7DD8cQg+eQId9Dm22Awfi54fsa7YNPZPAn9guPIU2HJJfiKRwevXwF7aHvz6GLrTYAwIv4BBabJd9",
	"Cj22DT9Bi2Tfzu6zzwg8gR7bwaEtts122C7sE/iD+ACt6Zt8u6+5NpV+pVzNPy0so0voRgigC9eXlheW",
	"F+ZSwYGKKrZE8s5quPhVdfo8+rLRBgpZCEboB/+8LjbfOIhZcIxZg6OmVGkcG1h1GtEgxJqRy191p0kD",
	"DjCSOuEHSIFZL+EQbJn6F0g3QfuGEn9ha4Wbi3DUkQXnqlWlMdLsrEaj5tq4/spHMkuevMiNaD0cFQEk",
	"FVYQWJtCU/PaAy+gw3agBwf8+QvVmZGIKs0FxLGJ7uV/hDa0YJ/toqZ24Bn0YB9a0BXY0KzXLQ56GSoJ",
	"quhn0IF9pcpoG9wqrXWuGwp3jBU+S1rTKvdcZ6tQ3X5Flba9s7kwb7ykuIaXkoYx30FLrJh9lV5va6xE",
	"xEm5cLqkEI5x8Bwl3oVeXk0eIcTtsc+hw3Y5654V8VGnLHqI4ZCVAICIPuNdT2TXh1ugDG1XEAXtjX79",
	"w46CBO9kRusd39k8bsXL9C5sZTdyWVwfE93v4bbGVe4QRS4toHrKFsA1/hA68JRDDjwnsI8tKU8FNedP",
	"2QhE4D2G9venWFol9kcmcQ1Tg0E79tvQLfZDnYuAP5+MsWRyhKdsJdm8nk4aP7AdeME9yHG0iJlTp6bN",
	"tpGSNuH4zx6yXfmRO7jQFR8yIYcxe2Mlrb3IcgIdAvvsPrrFn0OLiIAjVlIelfRrqN+MBqoo/71PWS70",
	"p1TzQh1LX4zjM/I726LXZjtsBzrQIZOe/4bf4Iw/ZA9IGFkRrfHg7L0Pl6dKeFmng7yzy80goF6ECaoT",
	"tD2cX8eiRzweY59Ch8dRYyyh76HNIz72JXS4ZbbYHtvlomK70OHks3+DDl+KGK0MWMWHclocwtdZKDEe",
	"8IcDg7fL+MSrH7oVTBkXxoaTcLrXjk+ZE+//Cr1iu2wbhUH0bZhkkjuSU1jo7ScpHhP5xuiO6cnHpyrb",
	"9MrGpWfg77FdAi/YNqeITEJXOYCVRC2mBsfLcMAtPxcvk0l4AS14Ah3MG3FIeJCGZ2HdGBXJbS1H2fdI",
	"Uhd9vAM+HnocTKBH8MXPcAt9yHYJn4lMCmO5hI1dJolbQC7ZNcuth9Oytjd10+M78CP4D/gzfAP/B/9F",
	"bNUZNE2WRN9oskM/ZLtshz0gSlrwEwJXkknriERWFppEWfCyyFeehOfY3xI6lPs4c6wEFJiVlIxw3197",
	"juNj5kSVWftsWRkThlQivuoJz7YNh9Ajk3Kkznwzm3UlxGJssa8qirVq2z4J08iWg08gqjrebejP0IZn",
	"bE9szCiC+2NiNRhao0O6M8au6CPo4UZ0oHYdtoPbA9tGmBZO6AH04Hmp7pblbrlMTzpxW4ir3wpT/Flj",
	"2HdSI9vsS5UeegVSxApE0eVG7dF4QKeRF+7X9oqFp1vScJ1b7zcxKkgPbha9rWnpbF2aQHdrwiTcvZrM",
	"xBFT04Ffo5cuTSTfTkzf9OARplLaYk/mTEqxaJ/IiVWYYRKFQRwdYZ9H/Oiw6mMXnTMmTvBIZ+yUEvAn",
	"5fNlTyOdcsqwDJuEqDrQZQ84WozHNiYUh+2yPbZDeADMvX9UKcxgcNXaPhtvLOlqO3UUiwXWLYezRKQZ",
	"MNtXXOQ7ApqyKPHz3zpizmcY98U4mGM6tMhkzIKpoTbnimztOTJeEdcjkwqyJvwG9Sampgn8gPGKQpZk",
	"jR14RuAhfKtDFXkM7W8DVnJn6k4AV7I9R/7tVHvYLd+vUau/ydq/revoKVZm0Woiy3hjiD6vUaYYZWQr",
	"EhxwXMjmVwj02C4cYAtTt8+neszDJ6L6jI6AKLKZrDzNPB8/eYrmftJhatJrN1rGlEsAsRx+knn/Huz/",
	"7PMrZ1Q2H8HOykQoghRhXmxPU0RP7EVrTqmzNYOiaHWu5oSd1eT4jj6WPIBD9jVHGlFk/FkGtBo+DOUW",
	"6hqh+ubpd/l0+pWpM5xZdGweOQRWoegEmfv1vPhNH51eytUieDTcV+Tg8y/8eunKtWWcalWaVGiS61fn",
	"55av4LchWbqyrGLlCXlifULnp/7SrWXM7fgdSO1RqDMoR4xo7aIeLQsVZiZNg/kJ9oUKdNgOqvoX+GiH",
	"PRivqoYKas/e1Ux0nVRSGKLCwDZ08QvCfsc3m5jjY7ZhcmLePmMAZnvwY05DdQAcl2xwD4Gn2FWxzRFZ",
	"dFaocwBDYvPkYBzWbPepEyyj1nBnyeTMFIEnSFBbUE2UO0rQ/d9G397x7XXqiY0DbfCxCAXYHpGv/8eb",
	"3uS5qdhwU4lFLAwnSUVxnwf5Byzv9mUUU7Odn+KP5B/INhvuE9lQOE1wlW14zPbwuezuoMCZQOemh8p2",
	"iOENFwLeW0IkwuvQe0n4Sx/ER31e4URD7uTVKScvs6egipqvOvBEVD/ZtugB6GIY2oZueocQyrzN7gsc",
	"64hvku7TdO/T+NTAuXE8hQ4ccFUelz1jbDuNv1HCZ7ucUZ+KLhZ1vgnb2XL6MokhFH/gAHqkL3Lqg1HV",
	"dRIWV8tlH0l819AJZQD1N+OctgsXr/J1W8nfRFtJxkN5ivt+j+3oe0kSW9AZSOWevO5ma3CWLh7wzubQ",
	"efnkIp3xz9alTOQo6Trk/88+UafJueSRf0f0PkmOsfsjZS3KVJn7zepytWLkn4siy95QNwL1a3J2UfH8",
	"BDX5VfIK85cenXZNe+Cu8wMC/gHmrVBvD9DRfzFeZ8WuX1s864D/LGJ4taH0RfH6ErYSnchXsj0hWrYn",
	"jPv6tcXC+Fdn0XEevLIu74grtmV1i9x8cnHBSVhS0aV1p2xRqesb9FJLlRxSjdxqKzjzim0qxXD2VpWv",
	"3qTTJdvqGI3yr9KM1aVLCvRbV9JJ1LusKVKJWzZGvgqV0ePS3tdn5UdthMyyb7AKbuAFhYNUT1xheJJF",
	"xMwliXofm9viPvezCWY6H2O3Qgv/4YBBZ0HFzMTeoPZtMilPMiIFISVi6eI36JClxTnx4OpM2m7DzTCi",
	"9SzHAtdbT7cy9JWyONruY5PFl4JKjhQtts3uEwyyTJWN3FLHK2Efz17Gp3qSdKp8H1axUpkPOQ7x6RA6",
	"IhOiS27ymO1dRfNpxE/pKyRHjaCyRSB4/rrZQWTusjYvKistk0APfpQ106/xmGi7L2EGLdm3w76CzoBE",
	"WTPE3aRIp/8oiiXQTVqdJvhmh+nbx5iZSxWmBBHyf+whxyKV2G1NEaWtE2zvpjeJxwa6WEw5YDtqU1Vh",
	"4NQ00dpTJgvoOqIzmu99Jgn8GjWJ49cpeeOmJ3uXhP2hrbTheZGdXOdMeGfzmrgjbYjjrvI2taNttOIy",
	"t9NJamRurxs5r6E9U8wZ+TrHkc5x5JLTsaVUZJp6UJtQIYulkylxXmfB2Q0we/PajRWuXyEN7upzGou+",
	"bdWIQ+8S8YxhivuP8U602Uqlxn/f8MNo9mL1YhX/ARf5/j6I+H3+fDoP6UWvBcEqSHK3QOqgM6dSc4r6",
	"9+nDrin0yKYUQ93Qb9MppSfoL/woY59kcBJtamb499j/bwk90zfixbMljpVmsu+SMlbBStSVKZrBf+EY",
	"iMD7WF2L8TvowlNUlw6nhN1PHWQXvsrWytZfAwAA//+u8VjYGmsAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
