// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: archive.sql

package sqlc

import (
	"context"
)

const createArchiveEntry = `-- name: CreateArchiveEntry :one
INSERT INTO archive (id, case_id, defendant, final_verdict, sentence, classified_note)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, case_id, defendant, final_verdict, sentence, classified_note, archived_at
`

type CreateArchiveEntryParams struct {
	ID             string  `json:"id"`
	CaseID         *string `json:"case_id"`
	Defendant      string  `json:"defendant"`
	FinalVerdict   string  `json:"final_verdict"`
	Sentence       *string `json:"sentence"`
	ClassifiedNote *string `json:"classified_note"`
}

func (q *Queries) CreateArchiveEntry(ctx context.Context, arg CreateArchiveEntryParams) (Archive, error) {
	row := q.db.QueryRowContext(ctx, createArchiveEntry,
		arg.ID,
		arg.CaseID,
		arg.Defendant,
		arg.FinalVerdict,
		arg.Sentence,
		arg.ClassifiedNote,
	)
	var i Archive
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.Defendant,
		&i.FinalVerdict,
		&i.Sentence,
		&i.ClassifiedNote,
		&i.ArchivedAt,
	)
	return i, err
}

const getArchiveByID = `-- name: GetArchiveByID :one
SELECT id, case_id, defendant, final_verdict, sentence, classified_note, archived_at
FROM archive
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetArchiveByID(ctx context.Context, id string) (Archive, error) {
	row := q.db.QueryRowContext(ctx, getArchiveByID, id)
	var i Archive
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.Defendant,
		&i.FinalVerdict,
		&i.Sentence,
		&i.ClassifiedNote,
		&i.ArchivedAt,
	)
	return i, err
}

const listArchive = `-- name: ListArchive :many
SELECT id, case_id, defendant, final_verdict, sentence, classified_note, archived_at
FROM archive
ORDER BY archived_at DESC
LIMIT ? OFFSET ?
`

type ListArchiveParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListArchive(ctx context.Context, arg ListArchiveParams) ([]Archive, error) {
	rows, err := q.db.QueryContext(ctx, listArchive, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Archive{}
	for rows.Next() {
		var i Archive
		if err := rows.Scan(
			&i.ID,
			&i.CaseID,
			&i.Defendant,
			&i.FinalVerdict,
			&i.Sentence,
			&i.ClassifiedNote,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArchiveSafe = `-- name: UpdateArchiveSafe :one
UPDATE archive
SET sentence      = COALESCE(?, sentence),
    final_verdict = COALESCE(?, final_verdict)
WHERE id = ?
RETURNING id, case_id, defendant, final_verdict, sentence, classified_note, archived_at
`

type UpdateArchiveSafeParams struct {
	Sentence     *string `json:"sentence"`
	FinalVerdict string  `json:"final_verdict"`
	ID           string  `json:"id"`
}

func (q *Queries) UpdateArchiveSafe(ctx context.Context, arg UpdateArchiveSafeParams) (Archive, error) {
	row := q.db.QueryRowContext(ctx, updateArchiveSafe, arg.Sentence, arg.FinalVerdict, arg.ID)
	var i Archive
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.Defendant,
		&i.FinalVerdict,
		&i.Sentence,
		&i.ClassifiedNote,
		&i.ArchivedAt,
	)
	return i, err
}
