// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: case_opinions.sql

package sqlc

import (
	"context"
)

const createCaseOpinion = `-- name: CreateCaseOpinion :one
INSERT INTO case_opinions (id, case_id, prosecutor_id, preliminary_verdict, reasoning)
VALUES (?, ?, ?, ?, ?)
RETURNING id, case_id, prosecutor_id, preliminary_verdict, reasoning, filed_at
`

type CreateCaseOpinionParams struct {
	ID                 string `json:"id"`
	CaseID             string `json:"case_id"`
	ProsecutorID       string `json:"prosecutor_id"`
	PreliminaryVerdict string `json:"preliminary_verdict"`
	Reasoning          string `json:"reasoning"`
}

func (q *Queries) CreateCaseOpinion(ctx context.Context, arg CreateCaseOpinionParams) (CaseOpinion, error) {
	row := q.db.QueryRowContext(ctx, createCaseOpinion,
		arg.ID,
		arg.CaseID,
		arg.ProsecutorID,
		arg.PreliminaryVerdict,
		arg.Reasoning,
	)
	var i CaseOpinion
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.ProsecutorID,
		&i.PreliminaryVerdict,
		&i.Reasoning,
		&i.FiledAt,
	)
	return i, err
}

const getCaseOpinionByCase = `-- name: GetCaseOpinionByCase :one
SELECT id, case_id, prosecutor_id, preliminary_verdict, reasoning, filed_at
FROM case_opinions
WHERE case_id = ?
LIMIT 1
`

func (q *Queries) GetCaseOpinionByCase(ctx context.Context, caseID string) (CaseOpinion, error) {
	row := q.db.QueryRowContext(ctx, getCaseOpinionByCase, caseID)
	var i CaseOpinion
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.ProsecutorID,
		&i.PreliminaryVerdict,
		&i.Reasoning,
		&i.FiledAt,
	)
	return i, err
}
