// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: complaints.sql

package sqlc

import (
	"context"
)

const createComplaint = `-- name: CreateComplaint :one
INSERT INTO complaints (id, case_id, author_id, text)
VALUES (?, ?, ?, ?)
RETURNING id, case_id, author_id, text, evidence_url, evidence_data, created_at
`

type CreateComplaintParams struct {
	ID       string `json:"id"`
	CaseID   string `json:"case_id"`
	AuthorID string `json:"author_id"`
	Text     string `json:"text"`
}

func (q *Queries) CreateComplaint(ctx context.Context, arg CreateComplaintParams) (Complaint, error) {
	row := q.db.QueryRowContext(ctx, createComplaint,
		arg.ID,
		arg.CaseID,
		arg.AuthorID,
		arg.Text,
	)
	var i Complaint
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.AuthorID,
		&i.Text,
		&i.EvidenceUrl,
		&i.EvidenceData,
		&i.CreatedAt,
	)
	return i, err
}

const getComplaintByID = `-- name: GetComplaintByID :one
SELECT id, case_id, author_id, text, evidence_url, evidence_data, created_at
FROM complaints
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetComplaintByID(ctx context.Context, id string) (Complaint, error) {
	row := q.db.QueryRowContext(ctx, getComplaintByID, id)
	var i Complaint
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.AuthorID,
		&i.Text,
		&i.EvidenceUrl,
		&i.EvidenceData,
		&i.CreatedAt,
	)
	return i, err
}

const listComplaintsByCase = `-- name: ListComplaintsByCase :many
SELECT id, case_id, author_id, text, evidence_url, evidence_data, created_at
FROM complaints
WHERE case_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListComplaintsByCase(ctx context.Context, caseID string) ([]Complaint, error) {
	rows, err := q.db.QueryContext(ctx, listComplaintsByCase, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Complaint{}
	for rows.Next() {
		var i Complaint
		if err := rows.Scan(
			&i.ID,
			&i.CaseID,
			&i.AuthorID,
			&i.Text,
			&i.EvidenceUrl,
			&i.EvidenceData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComplaintEvidence = `-- name: UpdateComplaintEvidence :one
UPDATE complaints
SET evidence_url  = ?,
    evidence_data = ?
WHERE id = ?
RETURNING id, case_id, author_id, text, evidence_url, evidence_data, created_at
`

type UpdateComplaintEvidenceParams struct {
	EvidenceUrl  *string `json:"evidence_url"`
	EvidenceData *string `json:"evidence_data"`
	ID           string  `json:"id"`
}

func (q *Queries) UpdateComplaintEvidence(ctx context.Context, arg UpdateComplaintEvidenceParams) (Complaint, error) {
	row := q.db.QueryRowContext(ctx, updateComplaintEvidence, arg.EvidenceUrl, arg.EvidenceData, arg.ID)
	var i Complaint
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.AuthorID,
		&i.Text,
		&i.EvidenceUrl,
		&i.EvidenceData,
		&i.CreatedAt,
	)
	return i, err
}
