// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: directives.sql

package sqlc

import (
	"context"
)

const getDirectiveByCode = `-- name: GetDirectiveByCode :one
SELECT id, directive_code, secret_payload, classification, issued_at
FROM mtb_directives
WHERE directive_code = ?
LIMIT 1
`

func (q *Queries) GetDirectiveByCode(ctx context.Context, directiveCode string) (MtbDirective, error) {
	row := q.db.QueryRowContext(ctx, getDirectiveByCode, directiveCode)
	var i MtbDirective
	err := row.Scan(
		&i.ID,
		&i.DirectiveCode,
		&i.SecretPayload,
		&i.Classification,
		&i.IssuedAt,
	)
	return i, err
}

const listDirectivesPublic = `-- name: ListDirectivesPublic :many
SELECT id, directive_code, secret_payload, classification, issued_at
FROM mtb_directives
WHERE classification = 'public'
ORDER BY issued_at DESC
LIMIT ? OFFSET ?
`

type ListDirectivesPublicParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListDirectivesPublic(ctx context.Context, arg ListDirectivesPublicParams) ([]MtbDirective, error) {
	rows, err := q.db.QueryContext(ctx, listDirectivesPublic, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MtbDirective{}
	for rows.Next() {
		var i MtbDirective
		if err := rows.Scan(
			&i.ID,
			&i.DirectiveCode,
			&i.SecretPayload,
			&i.Classification,
			&i.IssuedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
